name: Workflow to get the secret(s) from AWS Secret Manager.
# - How to Run Python Scripts in GitHub Action Workflows, Data Engineering With Nick, 1.43K subscribers
#   https://www.youtube.com/watch?v=zk4bSTD8uWM

on:
  workflow_dispatch:
    inputs:
      language:
          type: choice
          options:
              - c#
              - c++
              - go
              - java
              - javascript
              - python
              - ruby
              - rust
          description: Select the language to run.

jobs:
  pre-action-step:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repository.
        uses: actions/checkout@v4
      - name: Print language
        run: | 
          echo "language selected is ${{ inputs.language }}"
  
  python-get-secret:
    needs: [pre-action-step]
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repository.
        uses: actions/checkout@v4

      - name: Setup Python 3.12.
        uses: actions/setup-python@v5
        with:
          python-version: '3.12' 

      - name: Install Python Dependencies.
        run: |
          echo "Install Python Dependencies."
          python -m pip install -r python3/requirements.txt

      - name: Run python python3/get-secret.py.
        run: |
            echo "Run python python3/get-secret.py."
            ls -la
            python python3/get-secret.py

